# See: Travis Support did recomment moving Android builds to GCE.
# Which is on 'precise' and has larger VMs: https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: required
dist: precise

notifications:
  irc: irc.freenode.org#feedhenry

language: android

jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.3
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

env:
  matrix:
    - ANDROID_EMULATOR="android-25" ANDROID_ABI="google_apis/armeabi-v7a" ANDROID_PKGS="addon-google_apis-google-25,sys-img-armeabi-v7a-google_apis-25"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
  - bash .travis-android-license-bugfix.sh

before_script:
  - echo y | android update sdk --no-ui --all --filter ${ANDROID_EMULATOR},${ANDROID_PKGS},build-tools-25.0.3
  - echo no | android create avd --force -n test -t "${ANDROID_EMULATOR}" --abi "${ANDROID_ABI}"
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

after_success:
  - ./gradlew coveralls

after_failure:
  - ./gradlew clean check --debug
